/* ──────────────────────────────────────────────────────────────────────
 * resume-data.js
 * Single structured source for the interactive resume.
 * Client names are abstracted to industry by design; the systems described
 * are real, and every technical claim maps to code I have actually shipped.
 * ──────────────────────────────────────────────────────────────────── */
export const RESUME = {
  person: {
    name: "Bharat Rameshwar",
    shortName: "Bharat",
    monogram: "BR",
    title: "SAP Development Architect",
    tagline: "Twenty years at SAP, most of it hands-on in ABAP and HANA, building the custom development the standard product did not cover. Lately, applying AI to enterprise problems, with results I can stand behind.",
    location: "Sydney, Australia",
    email: "bharat@bharatrameshwar.com",
    linkedin: "linkedin.com/in/bharatrameshwar",
  },

  intro: [
    "I am an SAP development architect. Twenty years at SAP, the majority of it hands-on in ABAP and SAP HANA across development and architecture, building custom solutions to meet the requirements the standard product did not address: HANA native development and AMDP, CDS views, BW and BI-IP, S/4HANA enhancement, migrations and upgrades. The work meant orienting fast inside unfamiliar codebases, debugging standard code to find the right enhancement points, and keeping custom developments stable across release cycles. More recently I moved into customer success on SAP BTP, driving strategy for the platform to augment S/4HANA and custom enterprise applications.",
    "Alongside that, my focus has shifted to applied AI, and to the problems that only surface once you try to ship it. How data stays private when a model has to read it. How a system fails safely instead of guessing. How an agent earns the right to act on someone's behalf. Those are the questions the work below is built around.",
  ],

  metrics: [
    { value: 20, suffix: " yrs", label: "Across SAP Labs India and SAP Australia" },
    { value: 1.2, prefix: "$", suffix: "M", label: "Upsell and cross-sell pipeline, per year", decimals: 1 },
    { value: 70, suffix: "%", label: "BTP consumption growth, year on year" },
    { value: 100, suffix: "%", label: "Customer renewals, every year" },
  ],

  // ── AI portfolio: four architecture experiments, products unnamed ──────
  aiPortfolio: {
    eyebrow: "Applied AI · architecture experiments",
    title: "Six experiments in applying AI to real work.",
    lede: "Outside the day job I build to learn, and to solve the enterprise problems I run into every week. Six systems, each a working architecture rather than a demo: making a business's data answerable, reasoning over sensitive data without ever holding it, turning scattered activity into a usable record, collapsing spoken conversation into structured notes, an always-on agent that can act on my behalf, and a money companion that keeps its arithmetic honest. A pattern runs through all of them: keep the model downstream of a deterministic core, so it interprets and phrases while the exact work is done by code you can audit.",
    experiments: [
      {
        id: "memory",
        anchor: "data",
        tag: "Experiment I",
        name: "Answering questions across the business's data",
        problem: "A simple business question, why did margin slip on this account, who approved this exception, what is our exposure to this supplier, has its answer spread across a dozen systems. The structured records sit in one place, the documents that explain them in another, and no single query joins the two.",
        approach: "A system that builds two indexes over the same enterprise data: a knowledge graph that links the entities, customers, products, contracts, transactions, and a vector index over the documents that describe them. A question is answered by hybrid retrieval, traversing the graph for the facts and searching vectors for the context, then grounding the model in both.",
        techniques: [
          "Entity resolution into a linked knowledge graph",
          "Vector embeddings over unstructured documents",
          "Hybrid retrieval: graph traversal plus semantic search (GraphRAG)",
          "Answers grounded in retrieved facts, with their lineage",
        ],
        lesson: "A vector index alone gives you plausible answers; a graph alone gives you exact ones. The value is in the join, the model reasoning over facts and context together.",
        useCase: "An account manager asks, in plain language, what has gone quiet on a customer and why. The system walks the graph from that customer through its open topics, the decisions taken, and the last engagement on each, and answers with the specifics and a link back to where each came from. The same question used to mean an hour across four systems.",
        safeguards: [
          { label: "Grounded, not recalled", text: "The model never answers from memory. It answers only from what the retrieval returned, and every claim is traceable back to the record it came from. If the facts are not in the estate, the honest answer is 'I do not have that', not a confident guess." },
          { label: "Retrieval over generation", text: "The graph supplies exact facts and the documents supply the context; the model's job is to phrase what was retrieved, not to invent it. This is the single biggest lever against hallucination: keep the model downstream of the facts." },
          { label: "Read-only by default", text: "The query path can read the estate and nothing more. An agent can ask questions all day; it cannot change a record. Anything that writes is a separate, deliberate, permissioned path." },
          { label: "Lineage you can audit", text: "Because answers cite their source records, a wrong answer is debuggable: you can see exactly which fact or document led the model astray, rather than shrugging at a black box." },
        ],
        diagram: {
          w: 1000, h: 540,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Source data", x: 8, w: 184 },
            { label: "Ingest", x: 200, w: 184 },
            { label: "Index", x: 392, w: 196 },
            { label: "Stores", x: 596, w: 200 },
            { label: "Retrieve & answer", x: 804, w: 188 },
          ],
          nodes: [
            { id: "md", label: "Master data", short: "customers, products", x: 24, y: 26, w: 152, h: 62, kind: "ingest",
              a: "Structured master data, customers, products, suppliers, is read in as the backbone entities.", b: "Master data is the spine the graph hangs on; everything else attaches to it.", tech: "CDC from source systems; upserts on natural + surrogate keys" },
            { id: "tx", label: "Transactions", short: "orders, invoices", x: 24, y: 96, w: 152, h: 62, kind: "ingest",
              a: "Transactional records, orders, invoices, movements, are ingested as the events between entities.", b: "Transactions are the edges of the graph: who did what, with whom, and when.", tech: "append-only event stream; modelled as timestamped edges" },
            { id: "doc", label: "Documents", short: "contracts, policies", x: 24, y: 166, w: 152, h: 62, kind: "ingest",
              a: "Unstructured documents, contracts, policies, specifications, are ingested for embedding.", b: "The why behind a fact almost always lives in a document, not a table.", tech: "OCR + layout parse; PDF, DOCX, HTML to clean text" },
            { id: "ops", label: "Operational data", short: "events, logs", x: 24, y: 236, w: 152, h: 62, kind: "ingest",
              a: "Operational data, logs and system events, is ingested to keep the picture current.", b: "A stale graph answers yesterday's question; operational feeds keep it live.", tech: "log + event ingestion, batched hourly" },
            { id: "ing", label: "Ingest & normalise", short: "classify, clean, align", x: 214, y: 96, w: 156, h: 126, kind: "guard",
              a: "Every source is normalised, classified, and aligned to a common model before indexing.", b: "Bad joins produce confident nonsense. Normalisation is where answer quality is won or lost.", tech: "schema mapping to a canonical model; survivorship keys assigned" },
            { id: "res", label: "Entity resolution", short: "dedupe, link", x: 408, y: 54, w: 164, h: 96, kind: "process",
              a: "Records that refer to the same real-world entity are resolved and merged into one node.", b: "Without resolution the same customer appears five times and the graph connects nothing.", tech: "blocking + fuzzy match (Jaro-Winkler) with survivorship rules" },
            { id: "emb", label: "Chunk & embed", short: "text to vectors", x: 408, y: 246, w: 164, h: 96, kind: "process",
              a: "Documents are split into chunks and turned into vector embeddings for semantic search.", b: "Embeddings let the system retrieve by meaning, not by exact keyword.", tech: "~500-token chunks with overlap; 1536-dim embeddings" },
            { id: "graph", label: "Knowledge graph", short: "entities + relationships", x: 624, y: 40, w: 156, h: 104, kind: "data",
              a: "Resolved entities and their relationships are stored as a queryable knowledge graph.", b: "A graph answers exact, multi-hop questions a vector index simply cannot.", tech: "labelled property graph; multi-hop traversal in Cypher" },
            { id: "vec", label: "Vector index", short: "semantic search", x: 624, y: 200, w: 156, h: 96, kind: "store",
              a: "Embeddings are indexed for fast semantic retrieval of the supporting context.", b: "The graph holds the facts; the vector index holds the explanation.", tech: "HNSW index, cosine similarity, top-k ANN" },
            { id: "ret", label: "Hybrid retrieval", short: "graph + vector", x: 828, y: 44, w: 150, h: 100, kind: "process",
              a: "A question triggers hybrid retrieval: graph traversal for the facts, vector search for the context.", b: "Neither index is enough alone. The answer lives in the join of the two.", tech: "graph subgraph + ANN recall, fused and reranked" },
            { id: "ans", label: "Grounded answer", short: "facts + context", x: 828, y: 198, w: 150, h: 96, kind: "output",
              a: "The model composes an answer grounded in the retrieved facts and documents, with their lineage.", b: "Grounding in retrieved evidence is what makes the answer auditable instead of merely plausible.", tech: "grounded generation, citations back to node IDs" },
            { id: "agent", label: "Agent / API", short: "asks in language · A2A", x: 828, y: 332, w: 150, h: 96, kind: "cloud",
              a: "An agent or application asks in natural language and gets a grounded, traceable answer back.", b: "Exposed as a tool, the business's data becomes something other systems and agents can query directly.", tech: "exposed over MCP and REST; language to query-plan" },
          ],
          edges: [
            { from: "md", to: "ing" }, { from: "tx", to: "ing" }, { from: "doc", to: "ing" }, { from: "ops", to: "ing" },
            { from: "ing", to: "res" }, { from: "ing", to: "emb" },
            { from: "res", to: "graph" }, { from: "emb", to: "vec" },
            { from: "graph", to: "ret" }, { from: "vec", to: "ret" },
            { from: "ret", to: "ans", fromSide: "b", toSide: "t" },
            { from: "ans", to: "agent", fromSide: "b", toSide: "t" },
            { from: "agent", to: "ret", fromSide: "l", toSide: "l", dash: true },
          ],
        },
      },
      {
        id: "privacy",
        anchor: "privacy",
        tag: "Experiment II",
        name: "Privacy-preserving AI on sensitive data",
        problem: "To act on a business process, an AI has to read the data inside it: customer records, financials, contracts, case notes. Most of that is sensitive, and almost none of it needs to reach a cloud model in the clear.",
        approach: "A reasoning pipeline that detects and disguises every sensitive entity before any cloud model sees the record, reasons over the stand-ins, and restores the real values only at the edge. Built to fail closed, hold no secrets, and prove when it slips. Every stage is a decision with an alternative I turned down.",
        techniques: [
          "Deterministic identity masking with stable synthetic stand-ins",
          "Fail-closed design: never send unmasked text on a guess",
          "Two-layer envelope encryption (AES-256-GCM) for credentials",
          "Raw data auto-deleted within a day; only the result is kept, encrypted at rest",
          "Prompt-injection screening on all untrusted input",
          "A string-matching canary that alarms if a real value leaks",
        ],
        lesson: "You cannot prove a masking system is perfect, so you do not claim it. You build the alarm that assumes it will miss one, and you fail closed everywhere else.",
        useCase: "A support assistant needs to read customer case notes to draft a reply, but those notes are full of names, account numbers, and contact details. The pipeline disguises every one of those before a cloud model sees the text, lets the model reason over the stand-ins, then restores the real values only on the user's own machine. The model does useful work; it never holds a real identity.",
        safeguards: [
          { label: "Fail closed, never on a guess", text: "If the system cannot reliably detect the sensitive entities in a piece of text, it stops and retries later. It never ships unmasked text on the hope that it was clean. A late answer is acceptable; a leaked name is not." },
          { label: "Assume the masking will miss one", text: "No detector is perfect, so a plain string-matching canary scans every output before it is saved or shown, and alarms if any real value survived. The system is designed around its own failure, not around a claim of perfection." },
          { label: "Hold no secrets", text: "Credentials are wrapped in two-layer encryption with a per-record key; raw source data is deleted within a day; only the distilled result is kept, encrypted. The safest data to lose is the data you never stored." },
          { label: "Every input is hostile", text: "Untrusted text is screened for embedded instructions before any reasoning. Content is treated as data to summarise, never as commands to obey, which is how you stop prompt injection from turning a helper into an attacker's tool." },
        ],
        diagram: {
          w: 1000, h: 560,
          detailLabels: { a: "The decision", b: "The alternative, rejected" },
          lanes: [
            { label: "Intake", x: 8, w: 188 },
            { label: "Screen", x: 200, w: 184 },
            { label: "Decide", x: 390, w: 192 },
            { label: "Mask", x: 588, w: 174 },
            { label: "Reason & verify", x: 770, w: 190 },
          ],
          nodes: [
            { id: "in", label: "Business record", short: "read-only intake", x: 24, y: 224, w: 156, h: 96, kind: "ingest",
              a: "The source system is connected read-only. The pipeline can read the record, and read is the only verb it has.", b: "Write access for convenience features. It was not worth turning a read-only integration into one that could change the system of record.", tech: "least-privilege read-only scopes; OAuth, no write grant" },
            { id: "inj", label: "Injection screen", short: "every input is hostile", x: 214, y: 110, w: 156, h: 82, kind: "guard",
              a: "Screen every message for embedded instructions before any reasoning. Content is data to summarise, never commands to obey.", b: "Trusting inbox content because it is the user's own mail. An inbox is full of mail other people sent you.", tech: "instruction / jailbreak classifier on every input" },
            { id: "sec", label: "Secret guard", short: "refuse secrets", x: 214, y: 300, w: 156, h: 82, kind: "guard",
              a: "Drop anything that looks like a password, one-time code, recovery phrase, or full card number. Checked twice: pattern match and model pass.", b: "Storing credentials securely so the app could be more helpful. The safest secret is the one you never hold.", tech: "regex + model pass; secrets dropped before storage" },
            { id: "det", label: "Entity detection", short: "fail closed", x: 404, y: 110, w: 164, h: 82, kind: "process",
              a: "Regex handles patterned fields, a model finds the rest: names, accounts, references. If detection cannot run reliably, the work stops.", b: "Degrade gracefully and accept the occasional miss. Silently sending unmasked entities to a model is not a posture you can defend.", tech: "regex for patterned fields, NER for the rest" },
            { id: "hold", label: "Hold + retry", short: "held, not guessed", x: 404, y: 300, w: 164, h: 80, kind: "guard",
              a: "When detection is unhealthy the text is held and retried on the next cycle, never sent on the hope it was clean.", b: "Pushing it through to avoid a delayed result. A late answer beats an unmasked name reaching a model.", tech: "circuit-breaker; exponential backoff, retry next cycle" },
            { id: "mask", label: "Deterministic mask", short: "stable synthetic stand-ins", x: 598, y: 104, w: 156, h: 98, kind: "process",
              a: "Replace every personal entity with a realistic, stable synthetic stand-in. The same value always maps to the same fake.", b: "A second model cleanup pass. A generative model asked to rewrite a document rewrites it, merging entities that never existed.", tech: "1:1 stable token map; single-token, whitespace-free" },
            { id: "map", label: "Per-record map", short: "sealed at the edge", x: 598, y: 300, w: 156, h: 82, kind: "store",
              a: "The real-to-fake mapping is sealed with a key unique to the record and never sent to any model.", b: "Letting the model carry context across the swap. The map is the one secret that must never leave the edge.", tech: "sealed with a per-record key; never leaves the edge" },
            { id: "model", label: "Cloud model", short: "reasons over a stranger", x: 786, y: 40, w: 158, h: 80, kind: "cloud",
              a: "The model only ever sees the disguised text. It reasons about a coherent stranger, and is held not to retain or train on it.", b: "Sending real text for marginal quality. It was never worth the data leaving the edge in the clear.", tech: "no-retention / no-train terms; masked text only" },
            { id: "unmask", label: "Edge un-mask", short: "restore at the edge", x: 786, y: 180, w: 158, h: 80, kind: "process",
              a: "After the model responds, real values are substituted back at the edge using the sealed per-record map.", b: "Letting the model handle its own substitution. Reversal is deterministic code, not a model.", tech: "literal string substitution at the edge" },
            { id: "canary", label: "Canary check", short: "assume it misses one", x: 786, y: 318, w: 158, h: 78, kind: "guard",
              a: "Before anything is saved or shown, a plain string-matcher scans for any stand-in that should have been reversed, and alarms.", b: "Trusting the masking and learning of a leak when a user spots a stranger's name. If the only detector is the user, you have none.", tech: "string-match scan for un-reversed tokens; alerts" },
            { id: "ephemeral", label: "Raw data", short: "wiped within a day", x: 404, y: 446, w: 164, h: 84, kind: "store",
              a: "Raw ingested records are deleted within a day, with a daily sweep as a backstop.", b: "Holding raw source data indefinitely. If it is needed again, it is re-read from the source.", tech: "lifecycle TTL under 24h; daily sweep backstop" },
            { id: "distill", label: "Durable result", short: "decisions, encrypted", x: 598, y: 446, w: 156, h: 84, kind: "store",
              a: "Only the useful result is kept, encrypted at rest and namespaced per record. The decision, not the raw data.", b: "Keeping raw records for reprocessing. A standing archive is the asset you least want to hold.", tech: "encrypted at rest; per-record namespacing" },
            { id: "keys", label: "Envelope encryption", short: "two-layer, AES-256-GCM", x: 786, y: 442, w: 158, h: 96, kind: "store",
              a: "Each connection gets its own data key, which encrypts the credential and is itself wrapped by a master key.", b: "One master key over everything. A single leak would then decrypt every record.", tech: "AES-256-GCM; per-record DEK wrapped by a master KEK" },
          ],
          edges: [
            { from: "in", to: "inj" }, { from: "in", to: "sec" },
            { from: "inj", to: "det" }, { from: "sec", to: "det", fromSide: "r", toSide: "l" },
            { from: "det", to: "mask" },
            { from: "det", to: "hold", fromSide: "b", toSide: "t", dash: true },
            { from: "hold", to: "det", fromSide: "l", toSide: "l", dash: true },
            { from: "map", to: "mask", fromSide: "t", toSide: "b" },
            { from: "mask", to: "model" },
            { from: "model", to: "unmask", fromSide: "b", toSide: "t" },
            { from: "map", to: "unmask", dash: true },
            { from: "unmask", to: "canary", fromSide: "b", toSide: "t" },
            { from: "canary", to: "distill", fromSide: "b", toSide: "r" },
            { from: "in", to: "ephemeral", fromSide: "b", toSide: "l", dash: true },
            { from: "keys", to: "map", fromSide: "l", toSide: "b", dash: true },
            { from: "keys", to: "distill", fromSide: "l", toSide: "r", dash: true },
          ],
        },
      },
      {
        id: "assimilate",
        anchor: "activity",
        tag: "Experiment III",
        name: "Turning scattered activity into a record",
        problem: "Where your time and attention actually go is invisible. The signal is spread across every app, window, and document you touch, and by the end of the week most of it is simply gone.",
        approach: "A local-first system that captures multi-modal activity, on-screen context plus periodic screenshots, classifies it with a local model, and assimilates the result into structured memory: the people, documents, links, and tickets behind the work. That memory becomes daily and weekly reports, and is queryable by an agent. It is the one of these four that is open source, so the architecture below is not a description, it is the running code.",
        techniques: [
          "Multi-modal capture: active window context plus periodic screenshots",
          "Local LLM classification and memory extraction, fully on-device",
          "Full-text search over a local SQLite store",
          "An MCP server so an agent can query your own activity",
        ],
        lesson: "Most of this category ships as a dashboard of charts nobody opens. The point is not the capture, it is the assimilation: a week of raw events collapsed into the handful of people, decisions, and threads you would actually want back.",
        useCase: "On Friday you cannot remember what ate Tuesday, or who you were going back and forth with about a particular decision. You ask the record, in plain language, and it answers from what it actually saw: the people, the documents, the thread. A week of attention becomes something you can query instead of something you lost.",
        safeguards: [
          { label: "Local-first, by default", text: "Capture, classification, and memory all run on the machine. A record this intimate, what you read and who you spoke to, should never depend on a vendor seeing it. Nothing leaves the device unless you explicitly send it somewhere." },
          { label: "A local model does the reading", text: "The classifier and the memory extraction run on a local LLM, so the raw screen content is reasoned over on-device, not shipped to an API. Privacy is a property of where the compute happens, not a promise in a policy." },
          { label: "You hold the off switch", text: "It is open source, the data sits in a plain local database you can inspect or delete, and a cleanup job ages it out. There is no hidden server-side copy to worry about because there is no server." },
          { label: "Grounded answers", text: "When the agent answers a question about your activity, it answers from the stored record, not from a guess about what you probably did. The record is the source of truth." },
        ],
        link: "https://github.com/bharatrameshwar/commonplace",
        diagram: {
          w: 1000, h: 540,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Capture", x: 8, w: 184 },
            { label: "Classify", x: 200, w: 184 },
            { label: "Assimilate", x: 392, w: 196 },
            { label: "Store", x: 596, w: 200 },
            { label: "Surface", x: 804, w: 188 },
          ],
          nodes: [
            { id: "ctx", label: "Active context", short: "app · window · URL", x: 24, y: 70, w: 152, h: 84, kind: "ingest",
              a: "The frontmost app, window title, and browser URL are sampled continuously.", b: "Lightweight signals describe most of what you are doing without touching content.", tech: "AppleScript via osascript, polled every 5s" },
            { id: "shot", label: "Screenshots", short: "periodic frames", x: 24, y: 200, w: 152, h: 84, kind: "ingest",
              a: "A screenshot is taken on an interval to capture the visual context the metadata misses.", b: "Some context only exists on screen; an image fills the gap a window title leaves.", tech: "macOS screencapture, every 30s, skipped when idle" },
            { id: "cls", label: "Local classifier", short: "categorise spans", x: 214, y: 104, w: 156, h: 132, kind: "process",
              a: "A local model groups raw activity into categories and writes a one-line description of each span.", b: "Classification is the first compression: thousands of events down to a handful of categories.", tech: "Ollama qwen3:8b, temp 0.1, JSON-only output" },
            { id: "ext", label: "Memory extraction", short: "people, docs, tickets, links", x: 408, y: 104, w: 164, h: 132, kind: "process",
              a: "A second pass pulls the entities out of each span: the people, documents, tickets, and links.", b: "The people and threads are what you actually want back later, not the raw timeline.", tech: "second local LLM pass; structured JSON" },
            { id: "db", label: "Local store", short: "search-ready, on device", x: 624, y: 120, w: 156, h: 100, kind: "store",
              a: "Spans and extracted memory are persisted locally and indexed for full-text search.", b: "Local-first keeps a record this personal private by default; nothing leaves the machine.", tech: "SQLite + FTS5 virtual tables, on device" },
            { id: "dash", label: "Dashboard & reports", short: "daily + weekly", x: 828, y: 40, w: 150, h: 96, kind: "output",
              a: "Daily timelines and weekly trends are rendered from the store: where the time actually went.", b: "A report you do not have to assemble is the only one you will actually read.", tech: "Flask; timeline, focus score, per-category trend" },
            { id: "digest", label: "Daily digest", short: "narrative summary", x: 828, y: 176, w: 150, h: 96, kind: "output",
              a: "On demand, the day is summarised into a short narrative of what happened.", b: "Sometimes you want the story, not the chart.", tech: "on-demand local LLM summary" },
            { id: "mcp", label: "MCP server", short: "ask your activity", x: 828, y: 312, w: 150, h: 96, kind: "cloud",
              a: "An MCP server lets an agent query the record: what did I read about X, who did I last meet from Y.", b: "Once it is a tool, the record answers questions instead of just displaying them.", tech: "FastMCP; tools for search, day-context, screenshots" },
          ],
          edges: [
            { from: "ctx", to: "cls" }, { from: "shot", to: "cls" },
            { from: "cls", to: "ext" }, { from: "ext", to: "db" },
            { from: "db", to: "dash" }, { from: "db", to: "digest" }, { from: "db", to: "mcp" },
          ],
        },
      },
      {
        id: "scribe",
        anchor: "notes",
        tag: "Experiment IV",
        name: "Spoken conversation to structured notes",
        problem: "A conversation holds the decisions and the commitments, and then it is over. What is left is whatever someone half-remembered to write down.",
        approach: "A pipeline that turns speech into structured, searchable notes: transcription, speaker separation, then a model pass that distils the transcript into decisions, actions, and follow-ups. The decision that shaped everything else was to run the whole thing on-device. Audio is among the most sensitive material there is, and the moment it goes to a vendor to be processed, it has left your control. So it does not. Nothing is uploaded.",
        techniques: [
          "On-device speech-to-text, accelerated on Apple Silicon",
          "Speaker separation into attributed turns, on the Neural Engine",
          "Local model distillation into decisions and actions",
          "Audio and transcript never leave the machine",
        ],
        lesson: "Transcription is a commodity now; every platform has it. Keeping the audio on the machine while you do it is the part with a defensible reason behind it.",
        useCase: "You have spoken audio you are entitled to work with, and you want the decisions and actions out of it without the words ever leaving your machine. The pipeline transcribes, separates the speakers, and distils it to a short, searchable note, all on-device. The half-page that matters, with none of the data-residency questions that come the moment audio is uploaded.",
        safeguards: [
          { label: "On-device, end to end", text: "Capture, transcription, speaker separation, and distillation all run locally on the hardware. The audio and the transcript never touch a server, which removes the data-residency and retention questions before they can be asked." },
          { label: "Distil, do not embellish", text: "The model's job is to compress what was actually said into decisions and actions, not to add anything. It works from the transcript in front of it, so the output stays anchored to the real words rather than drifting into invention." },
          { label: "Consent is a precondition", text: "The system processes audio the user is entitled to process. The on-device design exists precisely so that sensitive recordings stay under the control of the person responsible for them, never handed to a third party." },
          { label: "Nothing to leak", text: "Because nothing is uploaded and the artefacts stay local, there is no cloud copy to breach, subpoena, or mishandle. The most private architecture is the one with no remote surface at all." },
        ],
        diagram: {
          w: 1000, h: 520,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Audio", x: 8, w: 184 },
            { label: "Transcribe", x: 200, w: 184 },
            { label: "Structure", x: 392, w: 196 },
            { label: "Distil", x: 596, w: 200 },
            { label: "Output", x: 804, w: 188 },
          ],
          nodes: [
            { id: "aud", label: "Audio in", short: "the conversation", x: 24, y: 205, w: 152, h: 100, kind: "ingest",
              a: "Spoken audio is taken in as the raw input to the pipeline.", b: "Speech is where the decisions are actually made; the notes are usually an afterthought.", tech: "native on-device audio capture" },
            { id: "asr", label: "Speech-to-text", short: "on-device ASR", x: 214, y: 95, w: 156, h: 96, kind: "process",
              a: "Audio is transcribed to text locally, accelerated on Apple Silicon rather than sent to a service.", b: "A cloud transcription API. Convenient, and the exact moment the audio leaves your control.", tech: "on-device ASR, hardware-accelerated" },
            { id: "diar", label: "Speaker separation", short: "who said what", x: 214, y: 250, w: 156, h: 96, kind: "process",
              a: "The audio is split by speaker so each turn is attributed, running on the Neural Engine.", b: "An action item means nothing if you cannot tell who committed to it.", tech: "on-device diarisation on the Neural Engine" },
            { id: "tx", label: "Transcript", short: "timestamped, labelled", x: 408, y: 175, w: 164, h: 110, kind: "data",
              a: "Transcription and speaker turns are aligned into one timestamped, labelled transcript.", b: "A clean transcript is the substrate the distillation step reasons over.", tech: "aligned, speaker-labelled text" },
            { id: "sum", label: "Local distillation", short: "the half-page that matters", x: 596, y: 175, w: 168, h: 110, kind: "process",
              a: "A local model distils the transcript into decisions, actions, and follow-ups.", b: "Nobody re-reads an hour of text; the value is the half-page it collapses into.", tech: "local model; structured extraction" },
            { id: "notes", label: "Structured notes", short: "decisions · actions", x: 804, y: 85, w: 172, h: 106, kind: "output",
              a: "The output is a structured, searchable note: decisions, owners, and next steps.", b: "Notes you can search and act on outlast any recording.", tech: "searchable structured notes" },
            { id: "store", label: "Local store", short: "stays on device", x: 804, y: 245, w: 172, h: 106, kind: "store",
              a: "Transcript and notes are kept locally; nothing is uploaded.", b: "On-device processing keeps a sensitive artefact under your control.", tech: "on-device; nothing leaves the machine" },
          ],
          edges: [
            { from: "aud", to: "asr" }, { from: "aud", to: "diar" },
            { from: "asr", to: "tx" }, { from: "diar", to: "tx" },
            { from: "tx", to: "sum" }, { from: "sum", to: "notes" },
            { from: "notes", to: "store", fromSide: "b", toSide: "t" },
          ],
        },
      },
      {
        id: "fen",
        anchor: "agent",
        tag: "Experiment V",
        name: "Fen, an always-on personal agent that can act",
        problem: "The useful things an assistant could do are scattered across the day and across systems: a message that needs a reply, a bill that just moved, a booking to make on a website. Ask a chat model to do them and you get plausible-sounding action with nothing behind it, no memory that survives the conversation, and no way to be sure it did what it said.",
        approach: "An always-on agent, Fen, running on my own server and reachable by voice from anywhere. The design decision that shapes everything else is that the model is kept out of the state. A deterministic reconciler is the only thing that writes; a bi-temporal commitment graph holds every promise and its timing so scheduling and money maths are exact; a calendar-aware scheduler decides when something is worth interrupting me for. The model interprets what I said and phrases what comes back. It never does the arithmetic and it never owns the truth.",
        techniques: [
          "Self-hosted, always-on agent, independent of any laptop",
          "HMAC-authenticated webhook ingress for voice and chat",
          "A deterministic reconciler as the single writer of state",
          "A bi-temporal commitment graph for exact scheduling and money maths",
          "A calendar-aware scheduler that batches and times notifications",
          "The LLM confined to interpretation and phrasing",
          "Browser automation with per-domain isolated auth profiles",
        ],
        lesson: "An agent earns the right to act by being boring where it counts. Put the model in charge of the state and it will confidently corrupt it; keep the state in deterministic code and the graph, and the model is free to be the flexible part without being the dangerous one.",
        useCase: "I say one line from wherever I am. The agent works out what I meant, checks it against what it already holds, and either does the thing or stages it. When something genuinely needs me, it waits for a gap between meetings and surfaces one triaged, deduplicated follow-up, instead of a scatter of pings all day. The state it acts on is a graph I can inspect, not a memory I have to trust.",
        safeguards: [
          { label: "The model never writes state", text: "Every change to what the agent knows or has promised goes through a deterministic reconciler, not the model. The model proposes; code decides and records. A hallucination can produce a wrong sentence, never a wrong commitment in the graph." },
          { label: "Locked to one person", text: "Access is an explicit allowlist of one. The agent answers to me and to nobody who happens to reach the endpoint. An open assistant that acts on your behalf is an open door; this one has a single key." },
          { label: "Isolated auth per site", text: "Browser automation keeps a separate, sandboxed credential profile per domain, so a problem on one site cannot reach into another. The blast radius of any single web task is that site and nothing else." },
          { label: "It waits its turn", text: "A presence and quiet-hours gate sits between a guardian finding something and my phone buzzing. Nothing interrupts me during a meeting or overnight unless it is genuinely time-critical, which is the difference between an assistant and a nuisance." },
        ],
        diagram: {
          w: 1000, h: 560,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Reach", x: 8, w: 184 },
            { label: "Ingress", x: 200, w: 184 },
            { label: "Decide", x: 392, w: 200 },
            { label: "Schedule", x: 600, w: 190 },
            { label: "Act", x: 798, w: 194 },
          ],
          nodes: [
            { id: "voice", label: "Voice / chat", short: "one line, from anywhere", x: 24, y: 224, w: 152, h: 96, kind: "ingest",
              a: "I reach the agent by voice or a short message from wherever I am, no app to open.", b: "The point of an always-on agent is that capturing a thought costs nothing; friction at the door means it never gets used.", tech: "chat + voice client; reaches the agent over the open web" },
            { id: "hook", label: "Webhook + HMAC", short: "authenticated ingress", x: 214, y: 120, w: 156, h: 90, kind: "guard",
              a: "Every inbound message hits a Cloudflare Worker that verifies an HMAC signature before anything runs.", b: "An always-on public endpoint is a target; signing every request is what stops anyone but me from driving the agent.", tech: "Cloudflare Worker; HMAC-signed webhook, rejected if unsigned" },
            { id: "allow", label: "Single-user gate", short: "allowlist of one", x: 214, y: 300, w: 156, h: 82, kind: "guard",
              a: "The request is checked against an allowlist of exactly one identity before it is accepted.", b: "An agent that can act on your behalf must answer to you alone; a broad allowlist is a broad attack surface.", tech: "explicit user allowlist; everything else dropped" },
            { id: "interp", label: "Interpret", short: "language to intent", x: 404, y: 116, w: 172, h: 90, kind: "process",
              a: "A model reads the message and works out what I actually want, turning loose language into a concrete intent.", b: "This is the one thing models are genuinely best at; using it here, and only here, keeps it away from the state.", tech: "LLM confined to interpretation; proposes, never commits" },
            { id: "recon", label: "Reconciler", short: "the only writer", x: 404, y: 236, w: 172, h: 96, kind: "process",
              a: "A deterministic reconciler takes the intent and is the single thing allowed to change what the agent knows or has promised.", b: "One writer, in code, means state can never be corrupted by a confident-but-wrong model. This is the spine of the whole design.", tech: "deterministic reconciler; sole writer, idempotent" },
            { id: "graph", label: "Commitment graph", short: "bi-temporal, exact", x: 404, y: 366, w: 172, h: 96, kind: "data",
              a: "Every promise, task, and bill lives in a bi-temporal graph that records both when a thing is due and when we learned it.", b: "Bi-temporal state is what makes scheduling and money maths exact and auditable, rather than a best guess from a prompt.", tech: "bi-temporal commitment graph; valid-time and record-time" },
            { id: "sched", label: "Attention scheduler", short: "calendar-aware", x: 610, y: 160, w: 170, h: 96, kind: "process",
              a: "A scheduler reads my calendar and decides whether now is a good moment to surface something, or whether to hold it.", b: "The gate between finding something and interrupting me is what turns a pile of alerts into one well-timed nudge.", tech: "calendar-aware; batches and ranks pending items" },
            { id: "gate", label: "Presence & quiet hours", short: "wait for a gap", x: 610, y: 300, w: 170, h: 90, kind: "guard",
              a: "Nothing reaches me during a meeting or overnight unless it is genuinely time-critical; the rest waits for a gap.", b: "An assistant that interrupts badly gets muted; timing is the difference between helpful and a nuisance.", tech: "presence + quiet-hours gate; fail-open to available" },
            { id: "phrase", label: "Phrase the reply", short: "model, downstream", x: 798, y: 116, w: 176, h: 90, kind: "process",
              a: "Once code has decided what happens, the model phrases the answer back in a consistent voice.", b: "Phrasing is downstream of the decision, so the words can be flexible while the action stays exact.", tech: "LLM for phrasing only; the figures come from the graph" },
            { id: "browser", label: "Browser automation", short: "isolated auth per site", x: 798, y: 236, w: 176, h: 96, kind: "cloud",
              a: "For real-world web tasks the agent drives a cloud browser, with a separate sandboxed login profile for each site.", b: "Per-domain isolation keeps a problem on one site from reaching another; the blast radius of any task is that site alone.", tech: "cloud browser; per-domain isolated auth profiles" },
            { id: "me", label: "One nudge, to me", short: "triaged, deduped", x: 798, y: 366, w: 176, h: 96, kind: "output",
              a: "What actually reaches me is a single, triaged, deduplicated follow-up at the right moment, not a scatter of pings.", b: "The output of all the machinery is calm: one thing worth my attention, phrased plainly, when I can act on it.", tech: "single delivered item; deduped on the graph key" },
          ],
          edges: [
            { from: "voice", to: "hook" },
            { from: "hook", to: "allow", fromSide: "b", toSide: "t" },
            { from: "hook", to: "interp" }, { from: "allow", to: "interp", fromSide: "r", toSide: "l" },
            { from: "interp", to: "recon", fromSide: "b", toSide: "t" },
            { from: "recon", to: "graph", fromSide: "b", toSide: "t" },
            { from: "graph", to: "recon", fromSide: "r", toSide: "r", dash: true },
            { from: "recon", to: "sched" },
            { from: "sched", to: "gate", fromSide: "b", toSide: "t" },
            { from: "recon", to: "browser", fromSide: "r", toSide: "l" },
            { from: "gate", to: "phrase", fromSide: "t", toSide: "l" },
            { from: "phrase", to: "me", fromSide: "b", toSide: "t" },
            { from: "browser", to: "me", fromSide: "b", toSide: "t" },
            { from: "graph", to: "sched", fromSide: "r", toSide: "b", dash: true },
          ],
        },
      },
      {
        id: "runway",
        anchor: "money",
        tag: "Experiment VI",
        name: "A money companion that keeps its arithmetic honest",
        problem: "The question that actually matters about money is a simple one: does what I have last until the next card payment. It is also surprisingly easy to get wrong, because an offset balance is not spendable, bills arrive on their own dates, and a few large irregular charges distort any simple average. Hand that to a language model and it will give you a confident number that is quietly incorrect.",
        approach: "Runway, a single-Worker companion that answers that one question in plain language. The arithmetic is the trust boundary, so the arithmetic is deterministic TypeScript: offset-as-buffer logic, recurring-bill date stepping, and lumpy-charge detection, unit tested and reviewed adversarially. The model is allowed nowhere near the maths. It cleans up messy merchant names and phrases the final sentence, and that is all. The figure it speaks is one the engine computed, verbatim.",
        techniques: [
          "A single Cloudflare Worker serving app, API, and cron",
          "A fully deterministic TypeScript engine for every calculation",
          "Offset-as-buffer, recurring-bill stepping, lumpy-charge detection",
          "The LLM confined to merchant-name cleanup and phrasing, never arithmetic",
          "KV storage; cron-driven sync from the PocketSmith API",
          "HMAC session auth; single-user by design",
        ],
        lesson: "Decide where the trust boundary is and defend it. For money the boundary is the arithmetic, so the arithmetic is code with tests around it, and the model is kept downstream doing the part where being approximately right is fine.",
        useCase: "One glance answers whether the money lasts until the card payment, already corrected for the offset that looks spendable but is not, and for the annual bills about to land. It is a plain sentence, not a spreadsheet, and the number in it was computed by tested code rather than guessed by a model.",
        safeguards: [
          { label: "The model never does the maths", text: "Every figure comes from a deterministic engine; the model only phrases the sentence around a number it was handed. The one thing you cannot afford to have hallucinated, the arithmetic, is the one thing the model is not allowed to touch." },
          { label: "The engine is tested and attacked", text: "The calculation engine is unit tested on a seeded fixture and was reviewed adversarially against its own edge cases: bills that skip February, transfers that look like spending, offset mistaken for cash. Trust in the number rests on those tests, not on a prompt." },
          { label: "Names cleaned at read time", text: "Merchant names are tidied when the data is read, not when it is stored, so the raw record stays intact and any cleanup mistake is inspectable and reversible rather than baked into history." },
          { label: "One person, one session", text: "It is single-user by design, gated by an HMAC session. A companion this close to your finances should have exactly one account it answers to, and no broader surface to defend." },
        ],
        diagram: {
          w: 1000, h: 520,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Feed", x: 8, w: 184 },
            { label: "Sync", x: 200, w: 184 },
            { label: "Engine", x: 392, w: 208 },
            { label: "Voice", x: 608, w: 180 },
            { label: "Surface", x: 796, w: 196 },
          ],
          nodes: [
            { id: "ps", label: "PocketSmith API", short: "the money feed", x: 24, y: 190, w: 152, h: 100, kind: "ingest",
              a: "Bank and card data, already aggregated and categorised, is read from the PocketSmith API.", b: "Someone else has solved bank aggregation well; building on it means the work here is the answer, not the plumbing.", tech: "PocketSmith developer API; read-only pull" },
            { id: "cron", label: "Cron sync", short: "scheduled, chunked", x: 214, y: 100, w: 156, h: 92, kind: "process",
              a: "A scheduled job pulls new transactions on a cron, in chunks to stay within request limits.", b: "A daily pre-computed picture means the answer is ready the moment I look, not assembled on the spot.", tech: "Worker cron; chunked backfill with a KV cursor" },
            { id: "kv", label: "KV store", short: "state + cursor", x: 214, y: 290, w: 156, h: 92, kind: "store",
              a: "Transactions, config, overrides, and the sync cursor are kept in key-value storage at the edge.", b: "Edge KV is enough for a single-user companion and keeps the whole thing inside one Worker with no database to run.", tech: "Workers KV; transactions, config, sync cursor" },
            { id: "offset", label: "Offset as buffer", short: "not spendable", x: 404, y: 60, w: 176, h: 84, kind: "process",
              a: "The offset balance is treated as a buffer that lowers interest, never as cash available to spend.", b: "Counting offset as spendable is the classic way to feel richer than you are; the engine refuses to make that mistake.", tech: "deterministic TS; offset excluded from spendable" },
            { id: "recur", label: "Recurring bills", short: "date stepping", x: 404, y: 158, w: 176, h: 84, kind: "process",
              a: "Recurring bills are projected forward by stepping real calendar dates, not by adding an average month.", b: "Adding 30.4 days quietly lies about which day a bill lands; stepping the actual date keeps the countdown honest.", tech: "day-of-month stepping; tolerates short-month gaps" },
            { id: "lumpy", label: "Lumpy charges", short: "discrete events", x: 404, y: 256, w: 176, h: 84, kind: "process",
              a: "Large irregular charges are detected as discrete dated events rather than smoothed into a daily average.", b: "A yearly insurance bill is not a little bit every day; treating it as an event is what stops the average from lying.", tech: "discrete lumpy-event detection over a long backfill" },
            { id: "engine", label: "Runway engine", short: "tested, adversarial", x: 404, y: 354, w: 176, h: 88, kind: "data",
              a: "The pieces combine into one figure: whether the money lasts to the card date, computed deterministically.", b: "Unit tested on a seeded fixture and reviewed against its own edge cases, because the number is the whole product.", tech: "deterministic engine; unit tests on a seeded fixture" },
            { id: "names", label: "Merchant cleanup", short: "read-time naming", x: 618, y: 120, w: 160, h: 90, kind: "process",
              a: "The model tidies messy raw payee strings into readable merchant names, at read time.", b: "Naming is a good fit for a model and safe here: it touches labels, never figures, and never the stored record.", tech: "LLM naming at read time; raw record untouched" },
            { id: "phrase", label: "Phrase the line", short: "figure verbatim", x: 618, y: 260, w: 160, h: 90, kind: "process",
              a: "The model writes the one plain sentence around the figure, which it must carry through verbatim.", b: "Phrasing is downstream of the maths; the model makes it readable but cannot change the number it was given.", tech: "LLM for phrasing; strict validation, figure verbatim" },
            { id: "answer", label: "The one sentence", short: "plain language", x: 806, y: 150, w: 176, h: 92, kind: "output",
              a: "The surface is a single line in plain language: does the money last, and what is worth knowing.", b: "One calm sentence is what someone actually reads; a dashboard of charts is what they close.", tech: "SPA served by the same Worker; one headline line" },
            { id: "session", label: "HMAC session", short: "single user", x: 806, y: 290, w: 176, h: 90, kind: "guard",
              a: "Access is gated by an HMAC session cookie; the companion answers to one account only.", b: "Something this close to your finances should have exactly one door and no wider surface to defend.", tech: "HMAC session cookie; single-user by design" },
          ],
          edges: [
            { from: "ps", to: "cron" },
            { from: "cron", to: "kv", fromSide: "b", toSide: "t" },
            { from: "kv", to: "offset", fromSide: "r", toSide: "l" },
            { from: "kv", to: "recur", fromSide: "r", toSide: "l" },
            { from: "kv", to: "lumpy", fromSide: "r", toSide: "l" },
            { from: "offset", to: "engine", fromSide: "b", toSide: "t" },
            { from: "recur", to: "engine", fromSide: "b", toSide: "t" },
            { from: "lumpy", to: "engine", fromSide: "b", toSide: "t" },
            { from: "engine", to: "names", fromSide: "r", toSide: "l" },
            { from: "engine", to: "phrase", fromSide: "r", toSide: "l" },
            { from: "names", to: "answer", fromSide: "r", toSide: "l" },
            { from: "phrase", to: "answer", fromSide: "r", toSide: "l" },
            { from: "session", to: "answer", fromSide: "t", toSide: "b", dash: true },
          ],
        },
      },
    ],
  },

  // ── Career timeline (scrub + expand). Sorted newest first. ────────────
  timeline: [
    {
      id: "csm",
      org: "SAP Australia",
      role: "Customer Success Manager, SAP BTP",
      sub: "incl. Datasphere, SAC and Business Data Cloud",
      start: 2021, end: null, range: "2021–present",
      summary: "Guiding net-new enterprise customers from on-premise SAP and non-SAP landscapes onto BTP and the data and analytics portfolio, with minimal disruption to the business.",
      points: [
        "Influenced 70% YoY BTP consumption growth and generated more than $1.2M of upsell and cross-sell pipeline in a single year.",
        "Positioned SAP Datasphere as the strategic data fabric and led competitive displacement of non-SAP data architectures in favour of Business Data Cloud.",
        "Demonstrated end-to-end BTP use cases by stringing services together: Integration Suite, Cloud Foundry-hosted CAP apps, identity, and HANA Cloud.",
        "Established a Centre of Excellence and architecture standards for BTP adoption, including governance and Fiori design guidelines.",
        "Served as the customer's advocate to SAP product teams, channelling feedback to influence the roadmap.",
      ],
      tags: ["BTP", "Data & Analytics", "Customer Success"],
    },
    {
      id: "fellow",
      org: "SAP Australia",
      role: "Fellowship, SAP Business AI Evangelist",
      sub: "concurrent fellowship",
      start: 2025, end: 2025, range: "2025",
      summary: "A fellowship enabling partners and customers on SAP Business AI across lines of business, and a proponent of an AI assistant as the new experience layer for business users.",
      points: [
        "Led partner enablement on Business AI features across line-of-business solutions.",
        "Ran Business AI workshops with global consulting partners to identify and shape customer use cases.",
        "Supported partner deals, helping articulate Business AI value to customers.",
      ],
      tags: ["Applied AI", "Enablement"],
    },
    {
      id: "architect",
      org: "SAP Australia",
      role: "Cloud Solution Architect",
      sub: "custom development",
      start: 2018, end: 2021, range: "2018–2021",
      summary: "Architecture lead for scalable enterprise solutions, with emphasis on intuitive interfaces and clean end-user workflows.",
      points: [
        "Architecture lead for a team of 10 developers delivering a high-quality enterprise planning solution.",
        "Led bespoke development for clients in property and defence, achieving a 30% lift in system efficiency through secure, fit-for-purpose architectures.",
        "Owned technical architecture decisions across data modelling, integration, scalability, and performance.",
      ],
      tags: ["Architecture", "BTP"],
    },
    {
      id: "labs",
      org: "SAP Labs India",
      role: "ABAP Solution Architect",
      sub: "custom development",
      start: 2008, end: 2018, range: "2008–2018",
      summary: "A decade delivering custom SAP implementations across manufacturing, transport, and retail on HANA, S/4HANA, and ECC.",
      points: [
        "Designed and delivered enterprise-scale solutions integrating multiple SAP modules with custom-built components.",
        "Led delivery teams of 4 to 13 as technical architect and scrum master across multiple long-running engagements.",
        "Mentored teams on SAP architecture, development methodology, and solution delivery.",
      ],
      tags: ["ABAP", "HANA", "Delivery"],
    },
    {
      id: "infosys",
      org: "Infosys Technologies",
      role: "Load Testing Script Author",
      sub: "",
      start: 2006, end: 2008, range: "2006–2007",
      summary: "Built automated testing frameworks for SAP GUI applications supporting enterprise-scale implementations. Moved straight to SAP Labs India with no break.",
      points: [
        "Developed frameworks for automated testing of SAP GUI and interaction with external test tooling.",
        "Partnered with QA to deliver performance benchmarking and scalable testing.",
      ],
      tags: ["Automation", "Quality"],
    },
  ],

  // Selected delivery projects. Clients abstracted to industry.
  projects: [
    {
      id: "cashflow",
      name: "40-year cashflow forecasting",
      industry: "ASX-listed property group",
      blurb: "A machine-learning solution on SAP Analytics Cloud, BI-IP, and HANA predicting cashflow forecasts to a 40-year horizon at GL-account level.",
      stack: ["SAP HANA", "BW/4HANA", "Analytics Cloud", "AMDP / CDS"],
      span: "2016–2020",
      role: "Solution Architect, team of 13",
    },
    {
      id: "edge",
      name: "Disconnected edge for field maintenance",
      industry: "national defence organisation",
      blurb: "A field-optimised solution for creating equipment maintenance documents with intermittent connectivity, validating master and transaction data offline.",
      stack: ["SAP Mobilink", "SQL Anywhere", "S/4HANA EAM"],
      span: "2021",
      role: "Solution Architect",
    },
    {
      id: "procure",
      name: "Intuitive procurement experience",
      industry: "national corrections agency",
      blurb: "Enhanced Fiori and GUI purchase requisition apps with role-based address restrictions, real-time address validation against external APIs, and dynamic, keyless vendor catalogue connections.",
      stack: ["SAP CAP", "Fiori Elements", "S/4HANA", "API Management"],
      span: "2021",
      role: "Solution Architect",
    },
    {
      id: "tm",
      name: "Transportation and freight management",
      industry: "global container shipping line",
      blurb: "Custom SAP TM execution across capacity, allocation, and routing, with BW extraction and reporting on the bespoke model. Technical architect and scrum master for a team of 7.",
      stack: ["SAP TM", "BOPF", "FPM", "BW on HANA"],
      span: "2015–2016",
      role: "Solution Architect & Scrum Master",
    },
    {
      id: "sd",
      name: "Sales and delivery integration",
      industry: "global horticulture exporter",
      blurb: "Custom SAP SD delivery and shipment management integrated with TM freight orders, with a modern UI5 front end on a Gateway and HANA foundation.",
      stack: ["SAP SD", "UI5", "Gateway", "HANA"],
      span: "2014–2015",
      role: "Technical Lead, team of 5",
    },
    {
      id: "pricing",
      name: "HANA-native pricing engine",
      industry: "Japanese industrial distributor",
      blurb: "Reimplemented SAP SD pricing logic on HANA and acted as the integration point between the HANA solution and an existing Java application.",
      stack: ["SAP HANA", "ABAP", "Java interface"],
      span: "2012–2013",
      role: "Senior Developer",
    },
  ],

  // ── Skills, grouped ───────────────────────────────────────────────────
  skillGroups: [
    {
      id: "dev",
      name: "SAP development & architecture",
      items: [
        "ABAP & ABAP on Cloud",
        "HANA native development & AMDP",
        "CDS views, BW & BI-IP",
        "SAP HANA modelling & performance optimisation",
        "S/4HANA custom development & enhancement",
        "Debugging & root cause analysis",
        "Migrations & upgrades",
        "SAP CAP & SAP Build",
      ],
    },
    {
      id: "ai",
      name: "Applied AI",
      items: [
        "Retrieval-augmented generation (RAG)",
        "Entity-graph modelling & resolution",
        "Deterministic data masking & de-identification",
        "Agent-to-agent (A2A) architecture",
        "Model Context Protocol (MCP) servers",
        "OpenAI, Anthropic & Perplexity API governance",
        "Prompt-injection defence & fail-closed design",
        "SAP Business AI, Joule Agents & BTP custom AI",
      ],
    },
    {
      id: "btp",
      name: "SAP BTP & extension",
      items: [
        "SAP Business Technology Platform",
        "Cloud Application Programming model (CAP)",
        "Integration Suite & API Management",
        "Event-driven architecture",
        "Fiori UX, Launchpad & role-based UI",
        "Cloud Foundry & CI/CD",
        "BTP credit estimation & consumption forecasting",
      ],
    },
    {
      id: "data",
      name: "Data & analytics",
      items: [
        "SAP Datasphere",
        "SAP Business Data Cloud (BDC)",
        "SAP Analytics Cloud (BI & Planning)",
        "SAP BW/4HANA & BI-IP",
        "SAP HANA Cloud & HANA 2.0",
        "Data modelling & migration strategy",
        "AMDP & CDS-based calculation",
      ],
    },
    {
      id: "cs",
      name: "Customer success",
      items: [
        "Executive stakeholder management",
        "Account ownership & renewals",
        "Upsell pipeline & churn reduction",
        "SaaS consumption & adoption",
        "De-escalation, major incident & root cause management",
        "Vendor & SI delivery accountability",
        "Partner enablement & cloud landscape advisory",
      ],
    },
  ],

  certifications: [
    { group: "SAP Certified Associate", items: ["Analytics Cloud Practitioner", "HANA Consultant", "Positioning SAP BTP", "Positioning the Autonomous Enterprise"] },
    { group: "SAP Technology Skills", items: ["Business Data Cloud", "Business AI & Joule Agents", "Extension Suite Black Belt", "Integration Black Belt"] },
    { group: "Solace certification", items: ["Event-Driven Architecture Practitioner", "Integration Associate"] },
    { group: "Google trainings", items: ["AI & Generative AI Foundations"] },
  ],

  // Verified credential badges.
  badges: [
    { img: "sap-data-analyst-sac.png", name: "Data Analyst, SAP Analytics Cloud", issuer: "SAP Certification" },
    { img: "sap-associate-sac.png", name: "Certified Associate, SAP Analytics Cloud", issuer: "SAP Certification" },
    { img: "sap-positioning-btp.png", name: "Positioning SAP Business Technology Platform", issuer: "SAP Certification" },
    { img: "sap-integration-black-belt-l3.png", name: "Integration Black Belt, Level 3", issuer: "SAP Technology Skills" },
    { img: "solace-eda-practitioner.png", name: "Event-Driven Architecture Practitioner", issuer: "Solace Academy" },
    { img: "google-generative-ai.png", name: "Introduction to Generative AI", issuer: "Google Cloud" },
  ],

  education: {
    degree: "Bachelor of Engineering, Mechanical Engineering",
    school: "Anna University, Chennai",
    span: "2002–2006",
  },

  // ── Community projects: things built for people, not for a client ──────
  community: [
    {
      id: "smallbiz",
      name: "Websites for small businesses",
      blurb: "Building and hosting websites for small businesses in the community on Cloudflare, end to end: domain, build, deploy, and the running cost kept near zero.",
      stack: ["Cloudflare Pages", "DNS", "Static site"],
    },
    {
      id: "productivity",
      name: "A personal productivity system",
      blurb: "An evolving set of AI agents that watch the inbox and calendar and surface what actually needs doing. The proving ground for most of the techniques in the experiments above.",
      stack: ["LLM agents", "MCP servers", "Vector search"],
    },
  ],

  closing: "The hard part of AI was never the model. It is the trust around it: how data stays safe, how a system fails well, how an answer earns belief. That is the work I want to keep doing.",
};
