/* ──────────────────────────────────────────────────────────────────────
 * resume-data.js
 * Single structured source for the interactive resume.
 * Client names are abstracted to industry by design; the systems described
 * are real, and every technical claim maps to code I have actually shipped.
 * ──────────────────────────────────────────────────────────────────── */
export const RESUME = {
  person: {
    name: "Bharat Rameshwar",
    shortName: "Bharat",
    monogram: "BR",
    title: "SAP BTP, Data & Applied AI",
    tagline: "Twenty years turning enterprise complexity into systems people can actually use. Lately, applying AI to enterprise problems, with results I can stand behind.",
    location: "Sydney, Australia",
    email: "bharat@bharatrameshwar.com",
    linkedin: "linkedin.com/in/bharatrameshwar",
  },

  intro: [
    "I help enterprises move from on-premise habits to a cloud that holds together. Twenty years of it, across SAP BTP, the data and analytics portfolio, and the custom development underneath.",
    "More recently my focus has shifted to applied AI, and to the problems that only surface once you try to ship it. How data stays private when a model has to read it. How a system fails safely instead of guessing. How an agent earns the right to act on someone's behalf. Those are the questions this work is built around.",
  ],

  metrics: [
    { value: 20, suffix: " yrs", label: "Across SAP Labs India and SAP Australia" },
    { value: 1.2, prefix: "$", suffix: "M", label: "Upsell and cross-sell pipeline, per year", decimals: 1 },
    { value: 70, suffix: "%", label: "BTP consumption growth, year on year" },
    { value: 100, suffix: "%", label: "Customer renewals, every year" },
  ],

  // ── AI portfolio: four architecture experiments, products unnamed ──────
  aiPortfolio: {
    eyebrow: "Applied AI · architecture experiments",
    title: "Four experiments in applying AI to real work.",
    lede: "Outside the day job I build to learn, and to solve the enterprise problems I run into every week. Four systems, each a working architecture rather than a demo: making a linked estate answerable, reasoning over sensitive data without ever holding it, turning scattered activity into a usable record, and collapsing spoken conversation into structured notes.",
    experiments: [
      {
        id: "memory",
        anchor: "estate",
        tag: "Experiment I",
        name: "Making a linked estate answerable",
        problem: "A simple question, who are the people on this account, what was decided and where did it stall, what has gone quiet, has its answer spread across a dozen records that no single query joins. The facts exist. What is missing is the structure that connects them and a way to ask in plain language.",
        approach: "A system that models the estate as a graph of linked entities, people, engagements, topics, the decisions and actions between them, and resolves new information into that graph rather than appending to a pile. A question is answered by traversing the graph: follow a topic across every engagement it touched, walk from a person to everything they were part of. The whole thing is exposed as a tool, so an agent can ask it directly. Every node below is a decision with an alternative I turned down.",
        techniques: [
          "Linked entity graph: people, engagements, topics, decisions, actions",
          "LLM entity resolution, new records matched and merged, not duplicated",
          "Multi-hop traversal: a topic followed across every engagement it touched",
          "Model-routed extraction, a cheap workhorse by default, a frontier model on demand",
          "Exposed over MCP so an agent queries the estate in natural language",
        ],
        lesson: "A pile of records answers nothing. The value is in the edges, the model resolving each new fact onto the entity it belongs to, so the graph is something you can actually walk.",
        diagram: {
          w: 1000, h: 540,
          detailLabels: { a: "The decision", b: "The alternative, rejected" },
          lanes: [
            { label: "Sources", x: 8, w: 184 },
            { label: "Extract", x: 200, w: 184 },
            { label: "Resolve", x: 392, w: 196 },
            { label: "Graph", x: 596, w: 200 },
            { label: "Answer", x: 804, w: 188 },
          ],
          nodes: [
            { id: "mtg", label: "Conversations", short: "transcripts, notes", x: 24, y: 40, w: 152, h: 60, kind: "ingest",
              a: "Meeting notes and transcripts come in as raw text, the richest record of what was actually said and decided.", b: "A structured form for every interaction. People do not fill in forms; the unstructured note is what actually exists.", tech: "free-text notes and transcripts, ingested as-is" },
            { id: "mail", label: "Email threads", short: "the back-and-forth", x: 24, y: 110, w: 152, h: 60, kind: "ingest",
              a: "Email threads are taken in as a second source, where commitments and objections usually surface.", b: "Asking the user to summarise each thread by hand. The thread already holds the signal; parse it, do not re-key it.", tech: "thread parser; quoted-reply and signature stripping" },
            { id: "doc", label: "Documents & files", short: "the artefacts", x: 24, y: 180, w: 152, h: 60, kind: "ingest",
              a: "Attached documents and pasted text are accepted as further context tied to the same entities.", b: "A separate document store off to the side. Context that is not attached to an entity is context nobody finds again.", tech: "drop / paste intake; OCR for image and PDF text" },
            { id: "ext", label: "LLM extraction", short: "text to structure", x: 214, y: 96, w: 156, h: 128, kind: "process",
              a: "A model reads each source and pulls out the structure: who was there, what was decided, what was committed, which topics moved.", b: "Regex and templates over the text. The shape of a real conversation defeats a template within a week.", tech: "schema-constrained extraction; strict JSON output" },
            { id: "route", label: "Model routing", short: "workhorse vs frontier", x: 214, y: 244, w: 156, h: 70, kind: "guard",
              a: "Routine extraction runs on a cheap, fast model; a frontier model is selected only when the work needs it.", b: "One large model for everything. Paying frontier prices for routine parsing is cost with no return.", tech: "default claude-haiku-4-5; opus / gpt-5 on demand" },
            { id: "res", label: "Entity resolution", short: "match or create", x: 408, y: 70, w: 164, h: 100, kind: "process",
              a: "Each extracted person and topic is matched against what already exists and merged, or created when genuinely new.", b: "Appending every extraction as a fresh row. Without resolution the same person and topic fork into a dozen near-duplicates.", tech: "deterministic name match, then LLM adjudication" },
            { id: "dedup", label: "Topic threading", short: "one thread, many touches", x: 408, y: 210, w: 164, h: 96, kind: "process",
              a: "A topic raised in one conversation is linked to every later one that touches it, building a single thread through time.", b: "Treating each mention as unrelated. The thread, not the mention, is what you want back later.", tech: "topic match by title + id; touchpoints over time" },
            { id: "graph", label: "Entity graph", short: "people · topics · decisions", x: 624, y: 70, w: 156, h: 110, kind: "data",
              a: "Resolved entities and their relationships are stored as a linked graph: people, engagements, topics, the decisions and actions between them.", b: "A flat table per record type. Relationships are the product here; a graph makes them first-class instead of implied.", tech: "relational store, foreign-key edges, junction tables" },
            { id: "trav", label: "Multi-hop traversal", short: "walk the edges", x: 624, y: 210, w: 156, h: 96, kind: "process",
              a: "A question becomes a walk over the graph: from a person to their engagements, along a topic across every touchpoint.", b: "A keyword search over the text. Search finds a mention; only traversal answers 'what happened to this, and who drove it'.", tech: "recursive joins across the entity edges" },
            { id: "mcp", label: "MCP server", short: "ask in language", x: 828, y: 70, w: 150, h: 100, kind: "cloud",
              a: "The estate is exposed as a set of tools, so an agent asks in natural language and gets a grounded, structured answer.", b: "A bespoke query UI for every question. As a tool, the estate answers questions nobody thought to build a screen for.", tech: "shipped MCP server; tools for journeys, topics, people" },
            { id: "ans", label: "Grounded answer", short: "traceable to records", x: 828, y: 210, w: 150, h: 96, kind: "output",
              a: "The answer is composed from what the traversal returned, traceable back to the engagements and people it came from.", b: "Letting the model answer from memory. An answer you cannot trace to a record is a guess wearing a suit.", tech: "answers built from retrieved rows, not model recall" },
          ],
          edges: [
            { from: "mtg", to: "ext" }, { from: "mail", to: "ext" }, { from: "doc", to: "ext" },
            { from: "ext", to: "route", fromSide: "b", toSide: "t", dash: true },
            { from: "route", to: "ext", fromSide: "l", toSide: "l", dash: true },
            { from: "ext", to: "res" }, { from: "ext", to: "dedup" },
            { from: "res", to: "graph" }, { from: "dedup", to: "graph" },
            { from: "graph", to: "trav", fromSide: "b", toSide: "t" },
            { from: "trav", to: "mcp", fromSide: "r", toSide: "l" },
            { from: "graph", to: "mcp" },
            { from: "mcp", to: "ans", fromSide: "b", toSide: "t" },
            { from: "trav", to: "ans" },
          ],
        },
      },
      {
        id: "privacy",
        anchor: "privacy",
        tag: "Experiment II",
        name: "Privacy-preserving AI on sensitive data",
        problem: "To act on a business process, an AI has to read the data inside it: customer records, financials, contracts, case notes. Most of that is sensitive, and almost none of it needs to reach a cloud model in the clear.",
        approach: "A reasoning pipeline that detects and disguises every sensitive entity before any cloud model sees the record, reasons over the stand-ins, and restores the real values only at the edge. Built to fail closed, hold no secrets, and prove when it slips. Every stage is a decision with an alternative I turned down.",
        techniques: [
          "Deterministic identity masking with stable synthetic stand-ins",
          "Fail-closed design: never send unmasked text on a guess",
          "Two-layer envelope encryption (AES-256-GCM) for credentials",
          "Raw data auto-deleted within a day; only the result is kept, encrypted at rest",
          "Prompt-injection screening on all untrusted input",
          "A string-matching canary that alarms if a real value leaks",
        ],
        lesson: "You cannot prove a masking system is perfect, so you do not claim it. You build the alarm that assumes it will miss one, and you fail closed everywhere else.",
        diagram: {
          w: 1000, h: 560,
          detailLabels: { a: "The decision", b: "The alternative, rejected" },
          lanes: [
            { label: "Intake", x: 8, w: 188 },
            { label: "Screen", x: 200, w: 184 },
            { label: "Decide", x: 390, w: 192 },
            { label: "Mask", x: 588, w: 174 },
            { label: "Reason & verify", x: 770, w: 190 },
          ],
          nodes: [
            { id: "in", label: "Business record", short: "read-only intake", x: 24, y: 224, w: 156, h: 96, kind: "ingest",
              a: "The source system is connected read-only. The pipeline can read the record, and read is the only verb it has.", b: "Write access for convenience features. It was not worth turning a read-only integration into one that could change the system of record.", tech: "least-privilege read-only scopes; OAuth, no write grant" },
            { id: "inj", label: "Injection screen", short: "every input is hostile", x: 214, y: 110, w: 156, h: 82, kind: "guard",
              a: "Screen every message for embedded instructions before any reasoning. Content is data to summarise, never commands to obey.", b: "Trusting inbox content because it is the user's own mail. An inbox is full of mail other people sent you.", tech: "instruction / jailbreak classifier on every input" },
            { id: "sec", label: "Secret guard", short: "refuse secrets", x: 214, y: 300, w: 156, h: 82, kind: "guard",
              a: "Drop anything that looks like a password, one-time code, recovery phrase, or full card number. Checked twice: pattern match and model pass.", b: "Storing credentials securely so the app could be more helpful. The safest secret is the one you never hold.", tech: "regex + model pass; secrets dropped before storage" },
            { id: "det", label: "Entity detection", short: "fail closed", x: 404, y: 110, w: 164, h: 82, kind: "process",
              a: "Regex handles patterned fields, a model finds the rest: names, accounts, references. If detection cannot run reliably, the work stops.", b: "Degrade gracefully and accept the occasional miss. Silently sending unmasked entities to a model is not a posture you can defend.", tech: "regex for patterned fields, NER for the rest" },
            { id: "hold", label: "Hold + retry", short: "held, not guessed", x: 404, y: 300, w: 164, h: 80, kind: "guard",
              a: "When detection is unhealthy the text is held and retried on the next cycle, never sent on the hope it was clean.", b: "Pushing it through to avoid a delayed result. A late answer beats an unmasked name reaching a model.", tech: "circuit-breaker; exponential backoff, retry next cycle" },
            { id: "mask", label: "Deterministic mask", short: "stable synthetic stand-ins", x: 598, y: 104, w: 156, h: 98, kind: "process",
              a: "Replace every personal entity with a realistic, stable synthetic stand-in. The same value always maps to the same fake.", b: "A second model cleanup pass. A generative model asked to rewrite a document rewrites it, merging entities that never existed.", tech: "1:1 stable token map; single-token, whitespace-free" },
            { id: "map", label: "Per-record map", short: "sealed at the edge", x: 598, y: 300, w: 156, h: 82, kind: "store",
              a: "The real-to-fake mapping is sealed with a key unique to the record and never sent to any model.", b: "Letting the model carry context across the swap. The map is the one secret that must never leave the edge.", tech: "sealed with a per-record key; never leaves the edge" },
            { id: "model", label: "Cloud model", short: "reasons over a stranger", x: 786, y: 40, w: 158, h: 80, kind: "cloud",
              a: "The model only ever sees the disguised text. It reasons about a coherent stranger, and is held not to retain or train on it.", b: "Sending real text for marginal quality. It was never worth the data leaving the edge in the clear.", tech: "no-retention / no-train terms; masked text only" },
            { id: "unmask", label: "Edge un-mask", short: "restore at the edge", x: 786, y: 180, w: 158, h: 80, kind: "process",
              a: "After the model responds, real values are substituted back at the edge using the sealed per-record map.", b: "Letting the model handle its own substitution. Reversal is deterministic code, not a model.", tech: "literal string substitution at the edge" },
            { id: "canary", label: "Canary check", short: "assume it misses one", x: 786, y: 318, w: 158, h: 78, kind: "guard",
              a: "Before anything is saved or shown, a plain string-matcher scans for any stand-in that should have been reversed, and alarms.", b: "Trusting the masking and learning of a leak when a user spots a stranger's name. If the only detector is the user, you have none.", tech: "string-match scan for un-reversed tokens; alerts" },
            { id: "ephemeral", label: "Raw data", short: "wiped within a day", x: 404, y: 446, w: 164, h: 84, kind: "store",
              a: "Raw ingested records are deleted within a day, with a daily sweep as a backstop.", b: "Holding raw source data indefinitely. If it is needed again, it is re-read from the source.", tech: "lifecycle TTL under 24h; daily sweep backstop" },
            { id: "distill", label: "Durable result", short: "decisions, encrypted", x: 598, y: 446, w: 156, h: 84, kind: "store",
              a: "Only the useful result is kept, encrypted at rest and namespaced per record. The decision, not the raw data.", b: "Keeping raw records for reprocessing. A standing archive is the asset you least want to hold.", tech: "encrypted at rest; per-record namespacing" },
            { id: "keys", label: "Envelope encryption", short: "two-layer, AES-256-GCM", x: 786, y: 442, w: 158, h: 96, kind: "store",
              a: "Each connection gets its own data key, which encrypts the credential and is itself wrapped by a master key.", b: "One master key over everything. A single leak would then decrypt every record.", tech: "AES-256-GCM; per-record DEK wrapped by a master KEK" },
          ],
          edges: [
            { from: "in", to: "inj" }, { from: "in", to: "sec" },
            { from: "inj", to: "det" }, { from: "sec", to: "det", fromSide: "r", toSide: "l" },
            { from: "det", to: "mask" },
            { from: "det", to: "hold", fromSide: "b", toSide: "t", dash: true },
            { from: "hold", to: "det", fromSide: "l", toSide: "l", dash: true },
            { from: "map", to: "mask", fromSide: "t", toSide: "b" },
            { from: "mask", to: "model" },
            { from: "model", to: "unmask", fromSide: "b", toSide: "t" },
            { from: "map", to: "unmask", dash: true },
            { from: "unmask", to: "canary", fromSide: "b", toSide: "t" },
            { from: "canary", to: "distill", fromSide: "b", toSide: "r" },
            { from: "in", to: "ephemeral", fromSide: "b", toSide: "l", dash: true },
            { from: "keys", to: "map", fromSide: "l", toSide: "b", dash: true },
            { from: "keys", to: "distill", fromSide: "l", toSide: "r", dash: true },
          ],
        },
      },
      {
        id: "assimilate",
        anchor: "activity",
        tag: "Experiment III",
        name: "Turning scattered activity into a record",
        problem: "Where your time and attention actually go is invisible. The signal is spread across every app, window, and document you touch, and by the end of the week most of it is simply gone.",
        approach: "A local-first system that captures multi-modal activity, on-screen context plus periodic screenshots, classifies it with a local model, and assimilates the result into structured memory: the people, documents, links, and tickets behind the work. That memory becomes daily and weekly reports, and is queryable by an agent. It is the one of these four that is open source, so the architecture below is not a description, it is the running code.",
        techniques: [
          "Multi-modal capture: active window context plus periodic screenshots",
          "Local LLM classification and memory extraction, fully on-device",
          "Full-text search over a local SQLite store",
          "An MCP server so an agent can query your own activity",
        ],
        lesson: "Most of this category ships as a dashboard of charts nobody opens. The point is not the capture, it is the assimilation: a week of raw events collapsed into the handful of people, decisions, and threads you would actually want back.",
        link: "https://github.com/bharatrameshwar/commonplace",
        diagram: {
          w: 1000, h: 540,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Capture", x: 8, w: 184 },
            { label: "Classify", x: 200, w: 184 },
            { label: "Assimilate", x: 392, w: 196 },
            { label: "Store", x: 596, w: 200 },
            { label: "Surface", x: 804, w: 188 },
          ],
          nodes: [
            { id: "ctx", label: "Active context", short: "app · window · URL", x: 24, y: 70, w: 152, h: 84, kind: "ingest",
              a: "The frontmost app, window title, and browser URL are sampled continuously.", b: "Lightweight signals describe most of what you are doing without touching content.", tech: "AppleScript via osascript, polled every 5s" },
            { id: "shot", label: "Screenshots", short: "periodic frames", x: 24, y: 200, w: 152, h: 84, kind: "ingest",
              a: "A screenshot is taken on an interval to capture the visual context the metadata misses.", b: "Some context only exists on screen; an image fills the gap a window title leaves.", tech: "macOS screencapture, every 30s, skipped when idle" },
            { id: "cls", label: "Local classifier", short: "categorise spans", x: 214, y: 104, w: 156, h: 132, kind: "process",
              a: "A local model groups raw activity into categories and writes a one-line description of each span.", b: "Classification is the first compression: thousands of events down to a handful of categories.", tech: "Ollama qwen3:8b, temp 0.1, JSON-only output" },
            { id: "ext", label: "Memory extraction", short: "people, docs, tickets, links", x: 408, y: 104, w: 164, h: 132, kind: "process",
              a: "A second pass pulls the entities out of each span: the people, documents, tickets, and links.", b: "The people and threads are what you actually want back later, not the raw timeline.", tech: "second local LLM pass; structured JSON" },
            { id: "db", label: "Local store", short: "search-ready, on device", x: 624, y: 120, w: 156, h: 100, kind: "store",
              a: "Spans and extracted memory are persisted locally and indexed for full-text search.", b: "Local-first keeps a record this personal private by default; nothing leaves the machine.", tech: "SQLite + FTS5 virtual tables, on device" },
            { id: "dash", label: "Dashboard & reports", short: "daily + weekly", x: 828, y: 40, w: 150, h: 96, kind: "output",
              a: "Daily timelines and weekly trends are rendered from the store: where the time actually went.", b: "A report you do not have to assemble is the only one you will actually read.", tech: "Flask; timeline, focus score, per-category trend" },
            { id: "digest", label: "Daily digest", short: "narrative summary", x: 828, y: 176, w: 150, h: 96, kind: "output",
              a: "On demand, the day is summarised into a short narrative of what happened.", b: "Sometimes you want the story, not the chart.", tech: "on-demand local LLM summary" },
            { id: "mcp", label: "MCP server", short: "ask your activity", x: 828, y: 312, w: 150, h: 96, kind: "cloud",
              a: "An MCP server lets an agent query the record: what did I read about X, who did I last meet from Y.", b: "Once it is a tool, the record answers questions instead of just displaying them.", tech: "FastMCP; tools for search, day-context, screenshots" },
          ],
          edges: [
            { from: "ctx", to: "cls" }, { from: "shot", to: "cls" },
            { from: "cls", to: "ext" }, { from: "ext", to: "db" },
            { from: "db", to: "dash" }, { from: "db", to: "digest" }, { from: "db", to: "mcp" },
          ],
        },
      },
      {
        id: "scribe",
        anchor: "notes",
        tag: "Experiment IV",
        name: "Spoken conversation to structured notes",
        problem: "A conversation holds the decisions and the commitments, and then it is over. What is left is whatever someone half-remembered to write down.",
        approach: "A pipeline that turns speech into structured, searchable notes: transcription, speaker separation, then a model pass that distils the transcript into decisions, actions, and follow-ups. The decision that shaped everything else was to run the whole thing on-device. Audio is among the most sensitive material there is, and the moment it goes to a vendor to be processed, it has left your control. So it does not. Nothing is uploaded.",
        techniques: [
          "On-device speech-to-text, accelerated on Apple Silicon",
          "Speaker separation into attributed turns, on the Neural Engine",
          "Local model distillation into decisions and actions",
          "Audio and transcript never leave the machine",
        ],
        lesson: "Transcription is a commodity now; every platform has it. Keeping the audio on the machine while you do it is the part with a defensible reason behind it.",
        diagram: {
          w: 1000, h: 520,
          detailLabels: { a: "What it does", b: "Why it is built this way" },
          lanes: [
            { label: "Audio", x: 8, w: 184 },
            { label: "Transcribe", x: 200, w: 184 },
            { label: "Structure", x: 392, w: 196 },
            { label: "Distil", x: 596, w: 200 },
            { label: "Output", x: 804, w: 188 },
          ],
          nodes: [
            { id: "aud", label: "Audio in", short: "the conversation", x: 24, y: 205, w: 152, h: 100, kind: "ingest",
              a: "Spoken audio is taken in as the raw input to the pipeline.", b: "Speech is where the decisions are actually made; the notes are usually an afterthought.", tech: "native on-device audio capture" },
            { id: "asr", label: "Speech-to-text", short: "on-device ASR", x: 214, y: 95, w: 156, h: 96, kind: "process",
              a: "Audio is transcribed to text locally, accelerated on Apple Silicon rather than sent to a service.", b: "A cloud transcription API. Convenient, and the exact moment the audio leaves your control.", tech: "on-device ASR, hardware-accelerated" },
            { id: "diar", label: "Speaker separation", short: "who said what", x: 214, y: 250, w: 156, h: 96, kind: "process",
              a: "The audio is split by speaker so each turn is attributed, running on the Neural Engine.", b: "An action item means nothing if you cannot tell who committed to it.", tech: "on-device diarisation on the Neural Engine" },
            { id: "tx", label: "Transcript", short: "timestamped, labelled", x: 408, y: 175, w: 164, h: 110, kind: "data",
              a: "Transcription and speaker turns are aligned into one timestamped, labelled transcript.", b: "A clean transcript is the substrate the distillation step reasons over.", tech: "aligned, speaker-labelled text" },
            { id: "sum", label: "Local distillation", short: "the half-page that matters", x: 596, y: 175, w: 168, h: 110, kind: "process",
              a: "A local model distils the transcript into decisions, actions, and follow-ups.", b: "Nobody re-reads an hour of text; the value is the half-page it collapses into.", tech: "local model; structured extraction" },
            { id: "notes", label: "Structured notes", short: "decisions · actions", x: 804, y: 85, w: 172, h: 106, kind: "output",
              a: "The output is a structured, searchable note: decisions, owners, and next steps.", b: "Notes you can search and act on outlast any recording.", tech: "searchable structured notes" },
            { id: "store", label: "Local store", short: "stays on device", x: 804, y: 245, w: 172, h: 106, kind: "store",
              a: "Transcript and notes are kept locally; nothing is uploaded.", b: "On-device processing keeps a sensitive artefact under your control.", tech: "on-device; nothing leaves the machine" },
          ],
          edges: [
            { from: "aud", to: "asr" }, { from: "aud", to: "diar" },
            { from: "asr", to: "tx" }, { from: "diar", to: "tx" },
            { from: "tx", to: "sum" }, { from: "sum", to: "notes" },
            { from: "notes", to: "store", fromSide: "b", toSide: "t" },
          ],
        },
      },
    ],
  },

  // ── Career timeline (scrub + expand). Sorted newest first. ────────────
  timeline: [
    {
      id: "csm",
      org: "SAP Australia",
      role: "Customer Success Manager, SAP BTP",
      sub: "incl. Datasphere, SAC and Business Data Cloud",
      start: 2021, end: null, range: "2021 — present",
      summary: "Guiding net-new enterprise customers from on-premise SAP and non-SAP estates onto BTP and the data and analytics portfolio, with minimal disruption to the business.",
      points: [
        "Influenced 70% YoY BTP consumption growth and generated more than $1.2M of upsell and cross-sell pipeline in a single year.",
        "Positioned SAP Datasphere as the strategic data fabric and led competitive displacement of non-SAP data architectures in favour of Business Data Cloud.",
        "Demonstrated end-to-end BTP use cases by stringing services together: Integration Suite, Cloud Foundry-hosted CAP apps, identity, and HANA Cloud.",
        "Established a Center of Excellence and architecture standards for BTP adoption, including governance and Fiori design guidelines.",
        "Served as the customer's advocate to SAP product teams, channelling feedback to influence the roadmap.",
      ],
      tags: ["BTP", "Data & Analytics", "Customer Success"],
    },
    {
      id: "fellow",
      org: "SAP Australia",
      role: "Fellowship — SAP Business AI Evangelist",
      sub: "concurrent fellowship",
      start: 2025, end: 2025, range: "2025",
      summary: "A fellowship enabling partners and customers on SAP Business AI across lines of business, and a proponent of an AI assistant as the new experience layer for business users.",
      points: [
        "Led partner enablement on Business AI features across line-of-business solutions.",
        "Ran Business AI workshops with global consulting partners to identify and shape customer use cases.",
        "Supported partner deals, helping articulate Business AI value to customers.",
      ],
      tags: ["Applied AI", "Enablement"],
    },
    {
      id: "architect",
      org: "SAP Australia",
      role: "Cloud Solution Architect",
      sub: "custom development",
      start: 2018, end: 2021, range: "2018 — 2021",
      summary: "Architecture lead for scalable enterprise solutions, with emphasis on intuitive interfaces and seamless end-user workflows.",
      points: [
        "Architecture lead for a team of 10 developers delivering a high-quality enterprise planning solution.",
        "Led bespoke development for clients in property and defence, achieving a 30% lift in system efficiency through secure, fit-for-purpose architectures.",
        "Owned technical architecture decisions across data modelling, integration, scalability, and performance.",
      ],
      tags: ["Architecture", "BTP"],
    },
    {
      id: "labs",
      org: "SAP Labs India",
      role: "ABAP Solution Architect",
      sub: "custom development",
      start: 2008, end: 2018, range: "2008 — 2018",
      summary: "A decade delivering custom SAP implementations across manufacturing, transport, and retail on HANA, S/4HANA, and ECC.",
      points: [
        "Designed and delivered enterprise-scale solutions integrating multiple SAP modules with custom-built components.",
        "Led delivery teams of 4 to 13 as technical architect and scrum master across multiple long-running engagements.",
        "Mentored teams on SAP architecture, development methodology, and solution delivery.",
      ],
      tags: ["ABAP", "HANA", "Delivery"],
    },
    {
      id: "infosys",
      org: "Infosys Technologies",
      role: "Load Testing Script Author",
      sub: "",
      start: 2006, end: 2008, range: "2006 — 2007",
      summary: "Built automated testing frameworks for SAP GUI applications supporting enterprise-scale implementations. Moved straight to SAP Labs India with no break.",
      points: [
        "Developed frameworks for automated testing of SAP GUI and interaction with external test tooling.",
        "Partnered with QA to deliver performance benchmarking and scalable testing.",
      ],
      tags: ["Automation", "Quality"],
    },
  ],

  // ── Selected delivery projects — clients abstracted to industry ───────
  projects: [
    {
      id: "cashflow",
      name: "40-year cashflow forecasting",
      industry: "ASX-listed property group",
      blurb: "A machine-learning solution on SAP Analytics Cloud, BI-IP, and HANA predicting cashflow forecasts to a 40-year horizon at GL-account level.",
      stack: ["SAP HANA", "BW/4HANA", "Analytics Cloud", "AMDP / CDS"],
      span: "2016 — 2020",
      role: "Solution Architect, team of 13",
    },
    {
      id: "edge",
      name: "Disconnected edge for field maintenance",
      industry: "national defence organisation",
      blurb: "A field-optimised solution for creating equipment maintenance documents with intermittent connectivity, validating master and transaction data offline.",
      stack: ["SAP Mobilink", "SQL Anywhere", "S/4HANA EAM"],
      span: "2021",
      role: "Solution Architect",
    },
    {
      id: "procure",
      name: "Intuitive procurement experience",
      industry: "national corrections agency",
      blurb: "Enhanced Fiori and GUI purchase requisition apps with role-based address restrictions, real-time address validation against external APIs, and dynamic, keyless vendor catalog connections.",
      stack: ["SAP CAP", "Fiori Elements", "S/4HANA", "API Management"],
      span: "2021",
      role: "Solution Architect",
    },
    {
      id: "tm",
      name: "Transportation and freight management",
      industry: "global container shipping line",
      blurb: "Custom SAP TM execution across capacity, allocation, and routing, with BW extraction and reporting on the bespoke model. Technical architect and scrum master for a team of 7.",
      stack: ["SAP TM", "BOPF", "FPM", "BW on HANA"],
      span: "2015 — 2016",
      role: "Solution Architect & Scrum Master",
    },
    {
      id: "sd",
      name: "Sales and delivery integration",
      industry: "global horticulture exporter",
      blurb: "Custom SAP SD delivery and shipment management integrated with TM freight orders, with a modern UI5 front end on a Gateway and HANA foundation.",
      stack: ["SAP SD", "UI5", "Gateway", "HANA"],
      span: "2014 — 2015",
      role: "Technical Lead, team of 5",
    },
    {
      id: "pricing",
      name: "HANA-native pricing engine",
      industry: "Japanese industrial distributor",
      blurb: "Reimplemented SAP SD pricing logic on HANA and acted as the integration point between the HANA solution and an existing Java application.",
      stack: ["SAP HANA", "ABAP", "Java interface"],
      span: "2012 — 2013",
      role: "Senior Developer",
    },
  ],

  // ── Skills, grouped ───────────────────────────────────────────────────
  skillGroups: [
    {
      id: "ai",
      name: "Applied AI",
      items: [
        "Retrieval-augmented generation (RAG)",
        "Entity-graph modelling & resolution",
        "Deterministic data masking & de-identification",
        "Agent-to-agent (A2A) architecture",
        "Model Context Protocol (MCP) servers",
        "OpenAI, Anthropic & Perplexity API governance",
        "Prompt-injection defence & fail-closed design",
        "SAP Business AI & BTP custom AI",
      ],
    },
    {
      id: "btp",
      name: "SAP BTP & extension",
      items: [
        "SAP Business Technology Platform",
        "Cloud Application Programming model (CAP)",
        "ABAP on Cloud",
        "SAP Build & low-code / no-code",
        "Integration Suite & API Management",
        "Event-driven architecture",
        "Fiori UX, Launchpad & role-based UI",
        "Cloud Foundry & CI/CD",
      ],
    },
    {
      id: "data",
      name: "Data & analytics",
      items: [
        "SAP Datasphere",
        "SAP Business Data Cloud (BDC)",
        "SAP Analytics Cloud (BI & Planning)",
        "SAP BW/4HANA & BI-IP",
        "SAP HANA Cloud & HANA 2.0",
        "Data modelling & migration strategy",
        "AMDP & CDS-based calculation",
      ],
    },
    {
      id: "cs",
      name: "Customer success",
      items: [
        "Executive stakeholder management",
        "Account ownership & renewals",
        "Upsell pipeline & churn reduction",
        "SaaS consumption & adoption",
        "De-escalation management",
        "Partner enablement",
        "Cloud landscape advisory",
      ],
    },
  ],

  certifications: [
    { group: "SAP Certified Associate", items: ["Analytics Cloud Practitioner", "HANA Consultant", "Positioning SAP BTP", "Positioning the Autonomous Enterprise"] },
    { group: "SAP Technology Skills", items: ["Business Data Cloud", "Business AI & Joule Agents", "Extension Suite Black Belt", "Integration Black Belt"] },
    { group: "Solace", items: ["Event-Driven Architecture Practitioner", "Integration Associate"] },
    { group: "Google", items: ["AI & Generative AI Foundations"] },
  ],

  // Verified credential badges.
  badges: [
    { img: "sap-data-analyst-sac.png", name: "Data Analyst — SAP Analytics Cloud", issuer: "SAP Certification" },
    { img: "sap-associate-sac.png", name: "Certified Associate — SAP Analytics Cloud", issuer: "SAP Certification" },
    { img: "sap-positioning-btp.png", name: "Positioning SAP Business Technology Platform", issuer: "SAP Certification" },
    { img: "sap-integration-black-belt-l3.png", name: "Integration Black Belt, Level 3", issuer: "SAP Technology Skills" },
    { img: "solace-eda-practitioner.png", name: "Event-Driven Architecture Practitioner", issuer: "Solace Academy" },
    { img: "google-generative-ai.png", name: "Introduction to Generative AI", issuer: "Google Cloud" },
  ],

  education: {
    degree: "Bachelor of Engineering, Mechanical Engineering",
    school: "Anna University, Chennai",
    span: "2002 — 2006",
  },

  closing: "The hard part of AI was never the model. It is the trust around it: how data stays safe, how a system fails well, how an answer earns belief. That is the work I want to keep doing.",
};
